services:
  - type: web
    name: enterprise-doc-assistant

    runtime: python

    buildCommand: |
      pip install -r requirements.txt

    startCommand: |
      streamlit run main.py --server.port $PORT --server.address 0.0.0.0

    envVars:
      - key: GEMINI_API_KEY
        sync: false

      - key: TOP_K_RESULTS
        value: "5"

      - key: CHUNK_SIZE
        value: "5000"

      - key: CHUNK_OVERLAP
        value: "200"